-- Rollback-only real PostgreSQL roles: no lasting test identities or provider sends.
begin;
create temporary table qa56_actors(name text,auth_id uuid,user_id text);
insert into qa56_actors select name,gen_random_uuid(),security.new_legacy_id('QA56') from unnest(array['owner','other','staff','student','employer','invalid']) name;
insert into auth.users(id,email,email_confirmed_at,aud,role,raw_app_meta_data,raw_user_meta_data)
select auth_id,'qa56-'||auth_id||'@example.invalid',now(),'authenticated','authenticated','{}','{}' from qa56_actors;
update qa56_actors a set user_id=u.user_id from public.users u where u.auth_user_id=a.auth_id;
insert into public.users(user_id,auth_user_id,email,first_name,last_name,status)
select a.user_id,a.auth_id,'qa56-'||auth_id||'@example.invalid','QA','Professional','active' from qa56_actors a where not exists(select 1 from public.users u where u.auth_user_id=a.auth_id);
update public.users set status='active' where user_id in (select user_id from qa56_actors);
insert into public.wf_institutions(institution_id,name,active) values('QA56-INS','QA Institution',true),('QA56-OTHER','Other Institution',true);
insert into public.wf_cohorts(cohort_id,institution_id,name,program_name,status) values('QA56-COHORT','QA56-INS','QA Cohort','QA Welding','active');
insert into public.app_role_memberships(membership_key,auth_user_id,user_id,role,scope_type,scope_id,status,source)
select 'qa56-'||name,auth_id,user_id,case name when 'staff' then 'support' when 'student' then 'student' when 'employer' then 'employer_admin' else 'instructor' end,
case name when 'staff' then 'platform' when 'student' then 'self' when 'employer' then 'employer' when 'invalid' then 'institution' else 'cohort' end,
case name when 'staff' then null when 'student' then 'QA56-STUDENT' when 'employer' then 'QA56-EMP' when 'invalid' then 'NO-INSTITUTION' else 'QA56-COHORT' end,'active','qa56' from qa56_actors;
grant select on qa56_actors to authenticated,service_role,anon;
create function pg_temp.actor(n text) returns void language plpgsql as $$ begin
 perform set_config('request.jwt.claim.sub',(select auth_id::text from qa56_actors where name=n),true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',(select auth_id from qa56_actors where name=n),'role','authenticated')::text,true);
end; $$;
create function pg_temp.ok(v boolean,label text) returns void language plpgsql as $$ begin if v is distinct from true then raise exception 'QA56 failed: %',label; end if; end; $$;
create function pg_temp.denied(q text,pattern text) returns void language plpgsql as $$ declare rejected boolean:=false; begin
 begin execute q; exception when others then if sqlerrm ~* pattern then rejected:=true; else raise; end if; end;
 perform pg_temp.ok(rejected,'expected denial '||pattern); end; $$;
create function pg_temp.settings(slug text,visibility text default 'public',prefs jsonb default '{"reviews":true,"ratings":true,"posts":true,"activity":true,"likes":true,"comments":true,"shares":true,"reposts":true}') returns jsonb language sql as $$
 select jsonb_build_object('slug',slug,'visibility',visibility,'displayName','QA Professional','headline','Educator','bio','<script>plain text</script>','specialties','Welding','credentials','Owner-entered license claim','preferences',prefs);
$$;
set local role authenticated;
select pg_temp.actor('owner');
select pg_temp.ok(public.professional_profile_settings('educator')->>'visibility'='private','private before opt-in');
select pg_temp.ok(public.professional_profile_settings('educator')->'preferences'->>'likes'='false','activity default hidden');
select pg_temp.ok(public.professional_profile_settings('educator')->'affiliations' @> '[{"name":"QA Institution","programs":["QA Welding"],"verified":true}]','canonical cohort program');
select pg_temp.denied('select public.professional_profile_settings(''staff'')','professional membership');
select pg_temp.denied('select public.professional_profile_settings(''educator'',pg_temp.settings(''qa56-owner'')||''{"affiliations":["Forged"]}'')','Unsupported');
select pg_temp.denied('select public.professional_profile_settings(''educator'',pg_temp.settings(''../../bad''))','URL');
select pg_temp.denied('select public.professional_profile_settings(''educator'',pg_temp.settings(''qa56-owner'')||''{"preferences":{"likes":true}}'')','visibility preference');
select public.professional_profile_settings('educator',pg_temp.settings('qa56-owner'));
select public.professional_post_save('educator','{"id":"POST-QA56-OWNER","title":"QA post","body":"Safe professional update","status":"published"}');
select pg_temp.denied('select public.professional_public_read(''/educators/qa56-owner'')','permission denied');
select pg_temp.denied('select * from public.wf_public_pages','permission denied');
select pg_temp.actor('other');
select pg_temp.denied('select public.professional_profile_settings(''educator'',pg_temp.settings(''qa56-owner''))','reserved');
select public.professional_profile_settings('educator',pg_temp.settings('qa56-other'));
select pg_temp.denied('select public.professional_post_save(''educator'',''{"id":"POST-QA56-OWNER","body":"Tampered","status":"removed"}'')','ownership');
select public.professional_post_save('educator','{"id":"POST-QA56-OTHER","body":"Another professional update","status":"published"}');
select pg_temp.actor('staff');
select public.professional_profile_settings('staff',pg_temp.settings('qa56-staff'));
select pg_temp.ok(public.professional_profile_settings('staff')->'affiliations' @> '[{"name":"TXKPRO","verified":true}]','support staff affiliation');
select pg_temp.denied('select public.professional_profile_settings(''educator'')','professional membership');
select pg_temp.actor('student');
select pg_temp.denied('select public.professional_profile_settings(''educator'')','professional membership');
select pg_temp.denied('select public.professional_profile_settings(''staff'')','professional membership');
select pg_temp.actor('employer');
select pg_temp.denied('select public.professional_profile_settings(''educator'')','professional membership');
select pg_temp.actor('invalid');
select pg_temp.denied('select public.professional_profile_settings(''educator'')','professional membership');
reset role;
create temporary table qa56_pages as select p.public_page_id,p.owner_user_id,a.name from public.wf_public_pages p join qa56_actors a on a.user_id=p.owner_user_id;
insert into public.wf_profile_reviews(target_public_page_id,reviewer_user_id,rating,review_body,status,moderation_metadata)
select p.public_page_id,a.user_id,case a.name when 'other' then 5 else 1 end,case a.name when 'other' then 'Published review' else 'PRIVATE_REVIEW' end,
case a.name when 'other' then 'published' else 'pending' end,'{"privateNote":"PRIVATE_MODERATION"}' from qa56_pages p cross join qa56_actors a where p.name='owner' and a.name in ('other','staff');
insert into public.wf_profile_post_reactions(profile_post_id,actor_user_id,actor_public_page_id)
select 'POST-QA56-OTHER',owner_user_id,public_page_id from qa56_pages where name='owner';
insert into public.wf_profile_post_comments(profile_post_id,author_user_id,author_public_page_id,body,status)
select 'POST-QA56-OTHER',owner_user_id,public_page_id,'Public comment','published' from qa56_pages where name='owner';
insert into public.wf_profile_post_comments(profile_post_id,author_user_id,author_public_page_id,body,status)
select 'POST-QA56-OTHER',owner_user_id,public_page_id,'PRIVATE_COMMENT','hidden' from qa56_pages where name='owner';
insert into public.wf_profile_post_shares(profile_post_id,actor_user_id,actor_public_page_id,share_type,commentary)
select 'POST-QA56-OTHER',owner_user_id,public_page_id,s,'Public share' from qa56_pages cross join unnest(array['share','repost']) s where name='owner';
grant select on qa56_pages to authenticated,service_role;
-- Owner customization and image registry use the same private/public ownership boundary.
insert into storage.objects(bucket_id,name,metadata)
select 'professional-profile',public_page_id||'/00000056-0000-4000-8000-000000000001','{"mimetype":"image/png","size":100}' from qa56_pages where name='owner';
set local role authenticated;
select pg_temp.actor('owner');
select public.professional_customization('educator',jsonb_build_object('op','image','slot','photo','storagePath',public.professional_customization('educator')->>'pageId'||'/00000056-0000-4000-8000-000000000001'));
select pg_temp.ok(public.professional_owner_image('educator','photo') is not null,'owner image access');
select public.professional_customization('educator','{"op":"layout","layout":"compact","panelOrder":["credentials","about","specialties","reviews","posts","activity"],"hiddenSections":["about","credentials"]}');
select pg_temp.denied('select public.professional_customization(''educator'',''{"op":"layout","layout":"compact","panelOrder":["about","about"],"hiddenSections":[]}'')','supported section');
select pg_temp.denied('select * from public.wf_professional_customization','permission denied');
select pg_temp.actor('other');
select pg_temp.denied('select public.professional_customization(''educator'',jsonb_build_object(''op'',''image'',''slot'',''photo'',''storagePath'',(select public_page_id from qa56_pages where name=''owner'')||''/00000056-0000-4000-8000-000000000001''))','Owned image');
select pg_temp.ok(public.professional_owner_image('educator','photo') is null,'foreign owner image not accessible');
set local role service_role;
select pg_temp.ok(public.professional_public_image('/educators/qa56-owner','photo') is not null,'public image for publishable profile');
select pg_temp.ok(public.professional_public_read('/educators/qa56-owner')->>'bio'='' and public.professional_public_read('/educators/qa56-owner')->>'credentials'='','hidden sections removed from public projection');
select pg_temp.ok(public.professional_public_read('/educators/qa56-owner')->'customization'->>'layout'='compact','layout persists publicly');
set local role authenticated;
select pg_temp.actor('owner');
select public.professional_customization('educator','{"op":"layout","layout":"comfortable","panelOrder":["about","specialties","credentials","reviews","posts","activity"],"hiddenSections":[]}');
select pg_temp.actor('other');
select public.professional_customization('educator','{"op":"layout","layout":"comfortable","panelOrder":["about","specialties","credentials","reviews","posts","activity"],"hiddenSections":["posts"]}');
set local role service_role;
select pg_temp.ok(jsonb_array_length(public.professional_public_read('/educators/qa56-owner')->'activity')=0,'hidden source Posts suppress history');
set local role authenticated;
select public.professional_customization('educator','{"op":"layout","layout":"comfortable","panelOrder":["about","specialties","credentials","reviews","posts","activity"],"hiddenSections":[]}');
reset role;
create temporary table qa56_audit as select count(*) n from public.platform_audit_events where action in ('PROFESSIONAL_PUBLIC_PROFILE_CHANGED','PROFESSIONAL_POST_CHANGED') and actor_user_id=(select user_id from qa56_actors where name='owner');
set local role authenticated;
select pg_temp.actor('owner');
select public.professional_profile_settings('educator',pg_temp.settings('qa56-owner'));
select public.professional_post_save('educator','{"id":"POST-QA56-OWNER","title":"QA post","body":"Safe professional update","status":"published"}');
reset role;
select pg_temp.ok((select count(*)=(select n from qa56_audit) from public.platform_audit_events where action in ('PROFESSIONAL_PUBLIC_PROFILE_CHANGED','PROFESSIONAL_POST_CHANGED') and actor_user_id=(select user_id from qa56_actors where name='owner')),'idempotent profile and post audits');
select pg_temp.ok(not exists(select 1 from public.platform_audit_events where action in ('PROFESSIONAL_PUBLIC_PROFILE_CHANGED','PROFESSIONAL_POST_CHANGED') and after_json::text like '%plain text%'),'no bio in audit');
set local role service_role;
select pg_temp.ok(public.professional_public_read('/educators/qa56-owner')->>'found'='true','public educator');
select pg_temp.ok(jsonb_array_length(public.professional_public_read('/educators/qa56-owner')->'posts')=1,'published post visible');
select pg_temp.ok(public.professional_public_read('/staff/qa56-staff')->>'found'='true','public staff');
select pg_temp.ok(public.professional_public_read('/educators/qa56-owner')->'rating'='{"average":5.0,"count":1}'::jsonb,'published ratings only');
select pg_temp.ok(jsonb_array_length(public.professional_public_read('/educators/qa56-owner')->'reviews')=1,'published reviews only');
select pg_temp.ok(jsonb_array_length(public.professional_public_read('/educators/qa56-owner')->'activity')=4,'all four public activity categories');
select pg_temp.ok(public.professional_public_read('/educators/qa56-owner')::text !~ 'PRIVATE_|auth_user_id|owner_user_id|reviewer_user_id|moderation_metadata','safe allowlist');
select pg_temp.ok(public.professional_public_sitemap() @> '[{"path":"/educators/qa56-owner"}]','sitemap includes publishable');
set local role authenticated;
select pg_temp.actor('owner');
select public.professional_profile_settings('educator',pg_temp.settings('qa56-owner','public','{"reviews":true,"ratings":true,"posts":true,"activity":true,"likes":true,"comments":true,"shares":true,"reposts":true}'::jsonb||jsonb_build_object('likes',false)));
set local role service_role;
select pg_temp.ok(not exists(select 1 from jsonb_array_elements(public.professional_public_read('/educators/qa56-owner')->'activity') a where a->>'type'='like'),'hide likes independently');
set local role authenticated;
select public.professional_profile_settings('educator',pg_temp.settings('qa56-owner','public','{"reviews":true,"ratings":true,"posts":true,"activity":true,"likes":true,"comments":true,"shares":true,"reposts":true}'::jsonb||jsonb_build_object('comments',false)));
set local role service_role;
select pg_temp.ok(not exists(select 1 from jsonb_array_elements(public.professional_public_read('/educators/qa56-owner')->'activity') a where a->>'type'='comment'),'hide comments independently');
set local role authenticated;
select public.professional_profile_settings('educator',pg_temp.settings('qa56-owner','public','{"reviews":true,"ratings":true,"posts":true,"activity":true,"likes":true,"comments":true,"shares":true,"reposts":true}'::jsonb||jsonb_build_object('shares',false)));
set local role service_role;
select pg_temp.ok(not exists(select 1 from jsonb_array_elements(public.professional_public_read('/educators/qa56-owner')->'activity') a where a->>'type'='share'),'hide shares independently');
set local role authenticated;
select public.professional_profile_settings('educator',pg_temp.settings('qa56-owner','public','{"reviews":true,"ratings":true,"posts":true,"activity":true,"likes":true,"comments":true,"shares":true,"reposts":true}'::jsonb||jsonb_build_object('reposts',false)));
set local role service_role;
select pg_temp.ok(not exists(select 1 from jsonb_array_elements(public.professional_public_read('/educators/qa56-owner')->'activity') a where a->>'type'='repost'),'hide reposts independently');
set local role authenticated;
select public.professional_profile_settings('educator',pg_temp.settings('qa56-owner','public','{"reviews":false,"ratings":false,"posts":false,"activity":false,"likes":true,"comments":true,"shares":true,"reposts":true}'));
set local role service_role;
select pg_temp.ok(public.professional_public_read('/educators/qa56-owner')->'reviews'='[]'::jsonb and public.professional_public_read('/educators/qa56-owner')->'posts'='[]'::jsonb and public.professional_public_read('/educators/qa56-owner')->'activity'='[]'::jsonb and public.professional_public_read('/educators/qa56-owner')->'rating'='null'::jsonb,'all presentation switches enforced');
set local role authenticated;
select public.professional_post_save('educator','{"id":"POST-QA56-OWNER","title":"QA post","body":"Safe professional update","status":"hidden"}');
set local role service_role;
select pg_temp.ok(jsonb_array_length(public.professional_public_read('/educators/qa56-owner')->'posts')=0,'hidden post excluded');
set local role authenticated;
select public.professional_post_save('educator','{"id":"POST-QA56-OWNER","title":"QA post","body":"Safe professional update","status":"draft"}');
set local role service_role;
select pg_temp.ok(jsonb_array_length(public.professional_public_read('/educators/qa56-owner')->'posts')=0,'draft post excluded');
set local role authenticated;
select public.professional_post_save('educator','{"id":"POST-QA56-OWNER","title":"QA post","body":"Safe professional update","status":"published"}');
select public.professional_profile_settings('educator',pg_temp.settings('qa56-owner-renamed'));
set local role service_role;
select pg_temp.ok(public.professional_public_read('/educators/qa56-owner')->>'redirect'='true','stable old URL');
set local role authenticated;
select pg_temp.actor('other');
select public.professional_profile_settings('educator',pg_temp.settings('qa56-other','private'));
set local role service_role;
select pg_temp.ok(jsonb_array_length(public.professional_public_read('/educators/qa56-owner-renamed')->'activity')=0,'private source excluded immediately');
set local role authenticated;
select pg_temp.actor('other');
select public.professional_profile_settings('educator',pg_temp.settings('qa56-other'));
select public.professional_post_save('educator','{"id":"POST-QA56-OTHER","body":"Another professional update","status":"removed"}');
select pg_temp.denied('select public.professional_post_save(''educator'',''{"id":"POST-QA56-OTHER","body":"Restored","status":"published"}'')','cannot be restored');
set local role service_role;
select pg_temp.ok(jsonb_array_length(public.professional_public_read('/educators/qa56-owner-renamed')->'activity')=0,'removed source excluded');
set local role authenticated;
select pg_temp.actor('owner');
select public.professional_profile_settings('educator',pg_temp.settings('qa56-owner-renamed','private'));
set local role service_role;
select pg_temp.ok(public.professional_public_read('/educators/qa56-owner')='{"found":false}'::jsonb,'old private URL gone');
select pg_temp.ok(public.professional_public_image('/educators/qa56-owner-renamed','photo') is null,'nonpublic image unavailable');
select pg_temp.ok(public.professional_public_read('/educators/qa56-owner-renamed')='{"found":false}'::jsonb,'current private URL gone');
select pg_temp.ok(not(public.professional_public_sitemap() @> '[{"path":"/educators/qa56-owner-renamed"}]'),'private excluded from sitemap');
set local role authenticated;
select pg_temp.actor('owner');
select public.professional_profile_settings('educator',pg_temp.settings('qa56-owner-renamed'));
reset role;
update public.app_role_memberships set status='inactive' where membership_key='qa56-owner';
set local role service_role;
select pg_temp.ok(public.professional_public_read('/educators/qa56-owner-renamed')='{"found":false}'::jsonb,'revoked membership removes public identity');
select pg_temp.ok(public.professional_public_read('/educators/qa56-owner')='{"found":false}'::jsonb,'revoked membership removes redirects');
set local role authenticated;
select pg_temp.actor('owner');
select pg_temp.denied('select public.professional_profile_settings(''educator'')','professional membership');
reset role;
update public.users set status='disabled' where user_id=(select user_id from qa56_actors where name='staff');
set local role service_role;
select pg_temp.ok(public.professional_public_read('/staff/qa56-staff')='{"found":false}'::jsonb,'disabled staff removed');
set local role anon;
select pg_temp.denied('select public.professional_profile_settings(''educator'')','permission denied');
select pg_temp.denied('select public.professional_post_save(''educator'',''{}'')','permission denied');
select pg_temp.denied('select public.professional_public_read(''/educators/qa56-owner'')','permission denied');
select pg_temp.denied('select public.professional_owner_image(''educator'',''photo'')','permission denied');
select pg_temp.denied('select public.professional_public_image(''/educators/qa56-owner'',''photo'')','permission denied');
select pg_temp.denied('select * from public.wf_profile_reviews','permission denied');
reset role;
select 'W12-17 customization QA PASS: roles, ownership, canonical affiliation, privacy, safe projection, published reviews, activity, redirects, sitemap, revocation, post transitions, audit idempotency' result;
rollback;
