-- Rollback-only fixture QA; no retained users/objects, no provider sends.
begin;
create temporary table qa223_actors(name text,auth_id uuid,user_id text);
insert into qa223_actors select name,gen_random_uuid(),security.new_legacy_id('QA223') from unnest(array['owner','other','staff','employer']) name;
insert into auth.users(id,email,email_confirmed_at,aud,role,raw_app_meta_data,raw_user_meta_data)
select auth_id,'qa223-'||auth_id||'@example.invalid',now(),'authenticated','authenticated','{}','{}' from qa223_actors;
update qa223_actors a set user_id=u.user_id from public.users u where u.auth_user_id=a.auth_id;
insert into public.users(user_id,auth_user_id,email,first_name,last_name,status)
select a.user_id,a.auth_id,'qa223-'||auth_id||'@example.invalid','QA','Portfolio','active' from qa223_actors a where not exists(select 1 from public.users u where u.auth_user_id=a.auth_id);
update public.users set status='active' where user_id in (select user_id from qa223_actors);
insert into public.app_role_memberships(membership_key,auth_user_id,user_id,role,scope_type,status,source)
select 'qa223-staff',auth_id,user_id,'admin','platform','active','qa223' from qa223_actors where name='staff';
create temporary table qa223_employer as select contractor_id from public.contractors where lower(approval_status)='approved' and lower(coalesce(account_status,'active'))='active' limit 1;
insert into public.app_role_memberships(membership_key,auth_user_id,user_id,role,scope_type,scope_id,status,source)
select 'qa223-employer',a.auth_id,a.user_id,'employer_admin','employer',e.contractor_id,'active','qa223' from qa223_actors a cross join qa223_employer e where a.name='employer';
update public.wf_employer_talent_scopes set active=false where employer_id in(select contractor_id from qa223_employer);
insert into public.wf_employer_talent_scopes(employer_id) select contractor_id from qa223_employer;
grant select on qa223_employer to authenticated,service_role,anon;
grant select on qa223_actors to authenticated,service_role,anon;
create function pg_temp.actor(n text) returns void language plpgsql as $$ begin
 perform set_config('request.jwt.claim.sub',coalesce((select auth_id::text from qa223_actors where name=n),''),true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',(select auth_id from qa223_actors where name=n),'role',case when n='anon' then 'anon' else 'authenticated' end)::text,true);
end; $$;
create function pg_temp.ok(v boolean,label text) returns void language plpgsql as $$ begin if v is distinct from true then raise exception 'QA223 failed: %',label; end if; end; $$;
create function pg_temp.denied(q text) returns void language plpgsql as $$ declare rejected boolean:=false; begin begin execute q; exception when others then rejected:=true; end; perform pg_temp.ok(rejected,'expected denial: '||q); end; $$;
set local role authenticated;
select pg_temp.actor('owner');
select public.complete_student_onboarding('{"firstName":"QA","lastName":"Portfolio","publicProfileVisibility":"public","publicProfileSlug":"qa223-owner","publicDisplayName":"QA Public","discoverable":false}');
select pg_temp.ok(public.student_portfolio()->'preferences'->>'rankingScope'='cohort','Cohort default');
select pg_temp.ok(public.student_portfolio()->'preferences'->>'showSkills'='false','public evidence opt-in');
select public.student_portfolio('{"op":"project_save","id":"00000223-0000-4000-8000-000000000001","title":"Welding portfolio","description":"<script>untrusted text</script>","skills":"MIG welding","visibility":"private"}');
select pg_temp.denied('select public.student_portfolio(''{"op":"preferences","rankingScope":"madeup"}'')');
select pg_temp.denied('select public.student_portfolio(''{"op":"file_register","id":"00000223-0000-4000-8000-000000000002","storagePath":"another-owner/path","title":"spoofed","kind":"resume","mime":"application/pdf","size":5}'')');
select pg_temp.denied('select public.student_portfolio_public(''/students/qa223-owner'')');
select pg_temp.denied('select * from public.wf_student_portfolio_files');
select pg_temp.actor('other');
select public.complete_student_onboarding('{"firstName":"Other","lastName":"Portfolio","publicProfileVisibility":"private","publicProfileSlug":"qa223-other","publicDisplayName":"Other"}');
select pg_temp.ok(jsonb_array_length(public.student_portfolio()->'projects')=0,'own projects only');
select pg_temp.denied('select public.student_portfolio(''{"op":"project_save","id":"00000223-0000-4000-8000-000000000001","title":"Tamper","visibility":"public"}'')');
select pg_temp.denied('select public.student_portfolio(''{"op":"project_delete","id":"00000223-0000-4000-8000-000000000001"}'')');
select pg_temp.actor('staff');
select pg_temp.denied('select public.student_portfolio()');
reset role;
create temporary table qa223_owner as select student_id from public.wf_student_profiles where user_id=(select user_id from qa223_actors where name='owner');
grant select on qa223_owner to authenticated,service_role,anon;
-- Canonical skill evidence fixture; raw evidence/private provenance are never projected.
insert into public.wf_student_skills(student_skill_id,student_id,skill_id,status,provenance,verified_at,verified_by_user_id,evidence_json)
select 'QA223-SKILL',o.student_id,sc.skill_id,'verified','institution_verified',now(),(select user_id from qa223_actors where name='staff'),'{"privateNotes":"DO_NOT_PUBLISH"}'::jsonb from qa223_owner o cross join (select skill_id from public.wf_skill_catalog limit 1) sc;
-- Simulate service-only validated storage registration without actual blob upload.
insert into storage.objects(bucket_id,name,metadata)
select 'student-portfolio',student_id||'/00000223-0000-4000-8000-000000000002','{"size":5,"mimetype":"application/pdf"}'::jsonb from public.wf_student_profiles where user_id=(select user_id from qa223_actors where name='owner');
set local role authenticated;
select pg_temp.actor('owner');
select public.student_portfolio(jsonb_build_object('op','file_register','id','00000223-0000-4000-8000-000000000002','storagePath',(public.student_portfolio()->>'studentId')||'/00000223-0000-4000-8000-000000000002','title','Resume','kind','resume','mime','application/pdf','size',5));
select pg_temp.ok(public.student_portfolio()->'files'->0->>'access'='private','uploads default private');
select pg_temp.denied('select public.student_portfolio(''{"op":"preferences","rankingScope":"cohort","photoId":"00000223-0000-4000-8000-000000000002"}'')');
select pg_temp.ok(public.student_portfolio_file('00000223-0000-4000-8000-000000000002') is not null,'owner private access');
select pg_temp.actor('other');
select pg_temp.ok(public.student_portfolio_file('00000223-0000-4000-8000-000000000002') is null,'other private denied');
select pg_temp.denied('select public.student_portfolio(''{"op":"file_update","id":"00000223-0000-4000-8000-000000000002","title":"Other","access":"public"}'')');
select pg_temp.actor('owner');
select public.student_portfolio('{"op":"file_update","id":"00000223-0000-4000-8000-000000000002","title":"Resume","access":"employer"}');
select pg_temp.actor('other');
select pg_temp.ok(public.student_portfolio_file('00000223-0000-4000-8000-000000000002','EMP-NOT-AUTHORIZED') is null,'role and scope required for Employer');
reset role;
update public.wf_student_profiles set discoverability_status='employer_discoverable' where user_id=(select user_id from qa223_actors where name='owner');
set local role authenticated;
select pg_temp.actor('employer');
select pg_temp.ok(public.student_portfolio_file('00000223-0000-4000-8000-000000000002',(select contractor_id from qa223_employer)) is not null,'authorized Employer file access');
select pg_temp.ok(jsonb_array_length(public.student_portfolio_employer_files((select student_id from qa223_owner),(select contractor_id from qa223_employer)))=1,'authorized Employer document list');
reset role;
update public.wf_student_profiles set discoverability_status='private' where user_id=(select user_id from qa223_actors where name='owner');
set local role authenticated;
select pg_temp.actor('employer');
select pg_temp.ok(public.student_portfolio_file('00000223-0000-4000-8000-000000000002',(select contractor_id from qa223_employer)) is null,'discovery consent revoked');
select pg_temp.actor('owner');
select public.student_portfolio('{"op":"file_update","id":"00000223-0000-4000-8000-000000000002","title":"Resume","access":"public"}');
select public.student_portfolio('{"op":"preferences","rankingScope":"institution","showSkills":true}');
select public.student_portfolio('{"op":"project_save","id":"00000223-0000-4000-8000-000000000001","title":"Welding portfolio","description":"Student-entered","skills":"MIG welding","visibility":"public"}');
reset role;
create temporary table qa223_count as select count(*) n from public.platform_audit_events where action='STUDENT_PORTFOLIO_CHANGED' and actor_user_id=(select user_id from qa223_actors where name='owner');
set local role authenticated;
select pg_temp.actor('owner');
select public.student_portfolio('{"op":"project_save","id":"00000223-0000-4000-8000-000000000001","title":"Welding portfolio","description":"Student-entered","skills":"MIG welding","visibility":"public"}');
reset role;
select pg_temp.ok((select count(*)=(select n from qa223_count) from public.platform_audit_events where action='STUDENT_PORTFOLIO_CHANGED' and actor_user_id=(select user_id from qa223_actors where name='owner')),'retry no duplicate audit');
select pg_temp.ok((select count(*)=1 from public.wf_student_portfolio_projects where id='00000223-0000-4000-8000-000000000001'),'retry no duplicate project');
select pg_temp.ok(not exists(select 1 from public.platform_audit_events where action='STUDENT_PORTFOLIO_CHANGED' and after_json::text ilike '%MIG%'),'audit no private text');
set local role service_role;
select pg_temp.ok(jsonb_array_length(public.student_portfolio_public('/students/qa223-owner')->'portfolio'->'projects')=1,'curated public projects');
select pg_temp.ok(public.student_portfolio_public('/students/qa223-owner')->'portfolio'->'evidence' @> '[{"category":"instructor_verified","status":"verified"}]','canonical verified skill projection');
select pg_temp.ok(public.student_portfolio_public('/students/qa223-owner')::text not like '%DO_NOT_PUBLISH%','skill private evidence excluded');
select pg_temp.ok(jsonb_array_length(public.student_portfolio_public('/students/qa223-owner')->'portfolio'->'files')=1,'public files only');
select pg_temp.ok(not (public.student_portfolio_public('/students/qa223-owner')->'portfolio' ? 'studentId'),'no raw student ID');
select pg_temp.ok(public.student_portfolio_public('/students/qa223-other')='{"found":false}','private page unavailable');
select pg_temp.ok(not (public.student_portfolio_public('/students/qa223-owner')::text like '%storagePath%'),'public no Storage path');
set local role service_role;
select pg_temp.actor('anon');
select pg_temp.ok(public.student_portfolio_public_file('00000223-0000-4000-8000-000000000002') is not null,'anonymous public file access');
set local role anon;
select pg_temp.denied('select public.student_portfolio()');
select pg_temp.denied('select public.student_portfolio_file(''00000223-0000-4000-8000-000000000002'')');
set local role authenticated;
select pg_temp.actor('owner');
select public.student_public_profile_settings('{"visibility":"private","slug":"qa223-owner","displayName":"QA"}');
set local role service_role;
select pg_temp.actor('anon');
select pg_temp.ok(public.student_portfolio_public_file('00000223-0000-4000-8000-000000000002') is null,'profile privacy revokes public file immediately');
set local role service_role;
select pg_temp.ok(public.student_portfolio_public('/students/qa223-owner')='{"found":false}','profile privacy hides projects immediately');
set local role authenticated;
select pg_temp.actor('owner');
select public.student_portfolio('{"op":"file_delete","id":"00000223-0000-4000-8000-000000000002"}');
select pg_temp.ok(public.student_portfolio_file('00000223-0000-4000-8000-000000000002') is null,'deleted file inaccessible');
reset role;
update public.users set status='disabled' where user_id=(select user_id from qa223_actors where name='owner');
set local role authenticated;
select pg_temp.actor('owner');
select pg_temp.denied('select public.student_portfolio()');
reset role;
select 'W12-16A authorization/privacy/portfolio QA passed; transaction rolled back' result;
rollback;
