"use client";
import {useState,type FormEvent} from "react";
import {useRouter} from "next/navigation";
import Link from "next/link";
import Image from "next/image";
import { ClassInstructors, CohortDates } from "@/components/classes/instructors";
import type { DirectoryData } from "@/components/classes/directory";
import {ActionModal,WorkspaceForm} from "@/components/design-system/action-modal";
import {PlusIcon,ArrowUpTrayIcon,UserPlusIcon} from "@heroicons/react/24/outline";
import type {ClassRecord,ClassWorkspace} from "@/lib/classes/server";
import type {RosterRow} from "@/lib/classes/roster";

async function post(path:string,body:unknown) {const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const p=await r.json();if(!r.ok) throw new Error(p.error??"Request failed");return p.data;}
export function ClassesWorkspace({data,people}:{data:ClassWorkspace;people:DirectoryData["people"]}) {
 const [requestKey,setRequestKey]=useState(()=>crypto.randomUUID()); const [message,setMessage]=useState(""); const [busy,setBusy]=useState(false); const router=useRouter();
 const manageable=data.cohorts.filter(c=>c.canManage);
 async function save(e:FormEvent<HTMLFormElement>,item?:ClassRecord) {e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);setMessage("");try{await post("/api/classes",{action:"save",input:{requestKey,classId:item?.classId,institutionId:f.get("institutionId"),name:f.get("name"),courseName:f.get("courseName"),status:f.get("status"),cohortIds:f.getAll("cohortIds")}});setMessage("Class saved.");setRequestKey(crypto.randomUUID());router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Unable to save");}finally{setBusy(false);}}
 return <div className="form-stack"><div className="institution-action-bar"><Link className="button" href="/institution/directory">Institution directory</Link>{manageable.length>0?<CohortDates cohorts={manageable}/>:null}{manageable.length>0?<WorkspaceForm modalTitle="Create class" busy={busy} onSubmit={e=>save(e)} className="form-stack"><p>Classes may include multiple cohorts. Your roster updates only after acceptance.</p><ClassFields cohorts={manageable}/><button className="button button-dark" disabled={busy}><PlusIcon width={20} aria-hidden="true"/>Create class</button></WorkspaceForm>:null}</div>
 {message?<p role="status" className="alert">{message}</p>:null}
 {!data.classes.length?<p className="card">No classes yet. An authorized instructor or coordinator can create one.</p>:null}
 {data.classes.map(item=><section className="card form-stack" key={item.classId}><div className="student-section-heading"><div><h2>{item.name}</h2><p className="card-sub">{item.courseName} · {item.status}</p></div>{item.canManage?<WorkspaceForm modalTitle="Edit class" busy={busy} onSubmit={e=>save(e,item)} className="form-stack"><ClassFields cohorts={[]} item={item}/><p>Cohort links are fixed after creation to protect existing roster scope.</p><button className="button button-dark" disabled={busy||item.status==="archived"}>Save</button></WorkspaceForm>:null}</div>
 <p className="card-sub">{item.cohorts.map(c=>`${c.program??"Program"} · ${c.name}`).join(" / ")}</p><p>Instructors: {item.instructors?.map(i=>i.name).join(", ")}</p>
 {item.canManage?<><ClassInstructors item={item} people={people}/><ClassInvites item={item}/></>:null}
 <h3>Roster</h3>{!item.enrollments.length?<p>No accepted students yet.</p>:item.enrollments.map(e=><div className="class-roster-row" key={e.userId}><span>{e.name} <span className="pill">{e.status}</span>{!e.studentId?<small> · Onboarding not completed</small>:null}</span>{item.canManage && e.status==="active"?<ActionModal title="Update enrollment" triggerLabel={`Manage ${e.name}`} busy={busy}><p>Withdraw or complete this enrollment. This does not change the student’s cohort or verified skills.</p>{["withdrawn","completed"].map(status=><button className="button" disabled={busy} key={status} onClick={async()=>{setBusy(true);try{await post("/api/classes",{action:"enrollment",classId:item.classId,userId:e.userId,status});router.refresh();setMessage("Enrollment updated.");}catch(e){setMessage(e instanceof Error?e.message:"Unable to update");}finally{setBusy(false);}}}>{status==="withdrawn"?"Withdraw":"Mark completed"}</button>)}</ActionModal>:null}</div>)}
 </section>)}
 </div>;
}
function ClassFields({cohorts,item}:{cohorts:ClassWorkspace["cohorts"];item?:ClassRecord}) {
 const institutions=[...new Set(cohorts.map(c=>c.institutionId))]; const [institution,setInstitution]=useState(item?.institutionId??institutions[0]??"");
 return <><label><span>Class name (required)</span><input className="input" name="name" required maxLength={120} defaultValue={item?.name}/></label><label><span>Course / subject (optional)</span><input className="input" name="courseName" maxLength={120} defaultValue={item?.courseName??""}/></label><label><span>Status</span><select className="select" name="status" defaultValue={item?.status??"draft"}>{["draft","open","closed","archived"].map(s=><option key={s}>{s}</option>)}</select></label>{!item?<><label><span>Institution</span><select className="select" name="institutionId" value={institution} onChange={e=>setInstitution(e.target.value)}>{institutions.map(i=><option key={i}>{i}</option>)}</select></label><fieldset><legend>Cohorts (select one or more)</legend>{cohorts.filter(c=>c.institutionId===institution).map(c=><label className="check-card" key={c.cohortId}><input type="checkbox" name="cohortIds" value={c.cohortId}/><span>{c.program} · {c.name}{c.startDate?` · ${c.startDate}`:""}</span></label>)}</fieldset></>:null}</>;
}
function ClassInvites({item}:{item:ClassRecord}) {
 const router=useRouter();const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");const [rows,setRows]=useState<RosterRow[]>([]);const [results,setResults]=useState<{email:string;ok:boolean;invitation?:{created:boolean};delivery?:{delivered:boolean}}[]>([]);const [join,setJoin]=useState<{url:string;qr:string}|null>(null);
 async function send(input:RosterRow[]) {setBusy(true);setMessage("");setResults([]);try{const all=[];for(let i=0;i<input.length;i+=10){setMessage(`Sending ${i+1}–${Math.min(i+10,input.length)} of ${input.length}…`);all.push(...await post("/api/classes/roster",{classId:item.classId,rows:input.slice(i,i+10)}));setResults([...all]);}setMessage("Invitation processing finished. Review delivery results below; pending invitations are not active students.");router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Unable to send");}finally{setBusy(false);}}
 async function invitationAction(id:string,action:string) {setBusy(true);try{await post(`/api/invitations/${encodeURIComponent(id)}/${action}`,{});setMessage(action==="resend"?"Resend processed.":"Invitation cancelled.");router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Unable to update");}finally{setBusy(false);}}
 return <><div className="institution-action-bar">
 <WorkspaceForm modalTitle="Invite student" busy={busy} className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void send([{email:String(f.get("email")),firstName:String(f.get("firstName")),lastName:String(f.get("lastName")),program:"",cohort:"",row:1}]);}}><p>Invitation to {item.name}. Student acceptance is required.</p>{[["email","Email (required)"],["firstName","First name"],["lastName","Last name"]].map(([name,label])=><label key={name}><span>{label}</span><input className="input" name={name} type={name==="email"?"email":"text"} required={name==="email"}/></label>)}<button className="button button-dark" disabled={busy||item.status!=="open"}><UserPlusIcon width={20} aria-hidden="true"/>Send invitation</button></WorkspaceForm>
 <ActionModal title="Upload roster" triggerLabel="Upload CSV / Excel" busy={busy}><div className="form-stack"><p>CSV or XLSX up to 2 MB / 1,000 students. Headers: email, first_name, last_name, program, cohort. Email is required; other columns are optional. Formulas are rejected.</p><a className="button" href="/class-roster-template.csv" download>Download CSV template</a><label><span>Roster file</span><input type="file" accept=".csv,.xlsx" disabled={busy} onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);setRows([]);setMessage("");try{const f=new FormData();f.set("classId",item.classId);f.set("file",file);const r=await fetch("/api/classes/roster",{method:"POST",body:f});const p=await r.json();if(!r.ok)throw new Error(p.error);setRows(p.data);}catch(e){setMessage(e instanceof Error?e.message:"Upload failed");}finally{setBusy(false);}}}/></label>{rows.length?<><p>{rows.filter(r=>!r.error).length} valid · {rows.filter(r=>r.error).length} flagged. Only valid rows will be invited.</p><div className="class-import-preview">{rows.map(r=><p key={r.row}>Row {r.row}: {r.email} · {r.error??"Ready"}{r.cohort?` · ${r.cohort}`:""}</p>)}</div><button className="button button-dark" disabled={busy||!rows.some(r=>!r.error)||item.status!=="open"} onClick={()=>send(rows.filter(r=>!r.error))}><ArrowUpTrayIcon width={20} aria-hidden="true"/>Confirm and invite valid rows</button></>:null}<p role="status">{message}</p>{results.map(r=><p key={r.email}>{r.email} · {!r.ok?"Failed — retry after correction":r.delivery?.delivered===false?"Recorded; email delivery failed — use Resend":r.invitation?.created===false?"Existing invitation; no duplicate":"Email sent"}</p>)}</div></ActionModal>
 <ActionModal title="Invite with QR code" triggerLabel="QR invitation" busy={busy}><div className="form-stack"><p>Reusable for seven days. Students must sign in and accept. Revoke the link to stop new claims.</p><button className="button" disabled={busy||item.status!=="open"} onClick={async()=>{setBusy(true);try{setJoin(await post("/api/classes",{action:"link",classId:item.classId}));router.refresh();}catch(e){setMessage(e instanceof Error?e.message:"Unable to create QR");}finally{setBusy(false);}}}>Create QR link</button>{join?<><Image unoptimized src={join.qr} alt={`QR invitation for ${item.name}`} width={240} height={240}/><a href={join.url}>{join.url}</a><button className="button" onClick={()=>navigator.clipboard.writeText(join.url).then(()=>setMessage("Link copied.")).catch(()=>setMessage("Select and copy the link manually."))}>Copy link</button><a href={join.qr} download="class-invitation.png" className="button">Download QR</a></>:null}{item.links.map(l=><div key={l.linkId}><p>{l.status} · Expires {new Date(l.expiresAt).toLocaleString()}</p>{l.status==="active"?<button className="button" disabled={busy} onClick={async()=>{setBusy(true);try{await post("/api/classes",{action:"revokeLink",classId:item.classId,linkId:l.linkId});setJoin(null);router.refresh();}catch(error){setMessage(error instanceof Error?error.message:"Unable to revoke link");}finally{setBusy(false);}}}>Revoke link</button>:null}</div>)}</div></ActionModal></div>
 {message?<p role="status" className="alert">{message}</p>:null}
 <details><summary>Invitations ({item.invitations.length})</summary>{item.invitations.map(v=><div className="class-roster-row" key={v.invitationId}><span>{v.email} · {v.status} · {v.deliveryStatus}</span>{v.status==="pending"?<div><button className="button" disabled={busy} onClick={()=>invitationAction(v.invitationId,"resend")}>Resend</button><button className="button" disabled={busy} onClick={()=>invitationAction(v.invitationId,"revoke")}>Cancel invitation</button></div>:null}</div>)}</details>
 </>;
}
