import type { Profile } from "@/lib/professional-profile/types";
export function ProfessionalProfileView({ profile }: { profile: Profile }) {
  return <div className="professional-profile">
    <article className="card professional-identity"><div className="professional-cover" aria-hidden="true" /><div className="professional-identity-content"><span className="pill">{profile.kind === "staff" ? "TXKPRO staff" : "Educator"}</span><h1>{profile.displayName}</h1><p className="professional-headline">{profile.headline}</p>{profile.affiliations.map((a, i) => <div key={`${a.name}-${i}`} className="professional-affiliation"><strong>{a.name}</strong> <span className="pill pill-good">Membership verified</span>{a.programs.length ? <p>{a.programs.join(" · ")}</p> : null}</div>)}</div></article>
    {profile.bio ? <section className="card"><h2>About</h2><p className="professional-text">{profile.bio}</p></section> : null}
    {profile.specialties ? <section className="card"><h2>Specialties</h2><div className="professional-pills">{profile.specialties.split(/\n/).filter(Boolean).map((s, i) => <span className="pill" key={i}>{s}</span>)}</div><p className="card-sub">Self-described specialties</p></section> : null}
    {profile.credentials ? <section className="card"><h2>Credentials</h2><span className="pill">Self-entered claims</span><p className="professional-text">{profile.credentials}</p><p className="card-sub">Supplied by the profile owner. Membership verification does not verify a credential or skill.</p></section> : null}
    {profile.rating || profile.reviews?.length ? <section className="card"><h2>Reviews</h2>{profile.rating ? <p><strong>{profile.rating.average} / 5</strong> · {profile.rating.count} published {profile.rating.count === 1 ? "review" : "reviews"}</p> : null}{profile.reviews?.map(r => <article className="professional-item" key={r.id}><strong>{r.reviewer} · {r.rating} / 5</strong>{r.verifiedRelationship ? <span className="pill pill-good">Relationship verified</span> : null}<h3>{r.title}</h3><p className="professional-text">{r.body}</p></article>)}</section> : null}
    {profile.posts.length ? <section className="card"><h2>Posts</h2>{profile.posts.map(p => <article id={p.id} className="professional-item" key={p.id}><h3>{p.title || "Update"}</h3><p className="professional-text">{p.body}</p>{p.publishedAt ? <time dateTime={p.publishedAt}>{new Date(p.publishedAt).toLocaleDateString("en-US", { timeZone: "UTC", year: "numeric", month: "short", day: "numeric" })}</time> : null}</article>)}</section> : null}
    {profile.activity?.length ? <section className="card"><h2>Activity</h2>{profile.activity.map((a, i) => <article className="professional-item" key={i}><p><strong>{a.type === "like" ? "Liked" : a.type === "comment" ? "Commented on" : a.type === "repost" ? "Reposted" : "Shared"}</strong> <a href={a.path}>{a.title || "an update"}</a> by {a.author}</p>{a.body ? <p className="professional-text">{a.body}</p> : null}</article>)}</section> : null}
  </div>;
}
