-- Execute with the migration in BEGIN/ROLLBACK. No email is sent or fixture retained.
do $$
declare e text; other_e text; owner_auth uuid; recipient_auth uuid; recipient_user text; recipient_email text; inv text; result jsonb; institution text; student_id text; checks integer:=0;
begin
 select m.scope_id,m.auth_user_id into e,owner_auth from public.app_role_memberships m join public.users u on u.auth_user_id=m.auth_user_id join public.contractors c on c.contractor_id=m.scope_id where u.status='active' and m.status='active' and m.role in ('employer_owner','employer_admin') and m.scope_type='employer' and c.account_status='active' and not exists(select 1 from public.app_role_memberships platform where platform.auth_user_id=m.auth_user_id and platform.status='active' and platform.scope_type='platform') limit 1;
 insert into public.contractors(business_name,account_status,approval_status) values('QA isolated employer','active','approved') returning contractor_id into other_e;
 select u.user_id,u.auth_user_id,u.email into recipient_user,recipient_auth,recipient_email from public.users u where lower(u.status)='active' and u.auth_user_id is not null and u.auth_user_id<>owner_auth and not exists(select 1 from public.contractors where owner_user_id=u.user_id) and not exists(select 1 from public.app_role_memberships m where m.auth_user_id=u.auth_user_id and m.status='active' and m.scope_type='platform') limit 1;
 if e is null or other_e is null or recipient_auth is null then raise exception 'QA fixtures unavailable';end if;
 delete from public.app_role_memberships where auth_user_id=recipient_auth and scope_type in ('employer','contractor');
 delete from public.contractor_team_members where user_id=recipient_user;
 perform set_config('request.jwt.claim.sub',owner_auth::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_auth,'email',(select email from public.users where auth_user_id=owner_auth),'role','authenticated')::text,true);
 if not security.user_invitation_actor_can_manage('employer_employee','employer',e,null,e) then raise exception 'Owner employee invitation denied';end if;checks:=checks+1;
 if security.user_invitation_actor_can_manage('employer_employee','institution',e,null,e) then raise exception 'Wrong scope allowed';end if;checks:=checks+1;
 if security.user_invitation_actor_can_manage('employer_employee','employer',other_e,null,other_e) then raise exception 'Cross employer invitation allowed';end if;checks:=checks+1;
 result:=security.user_invitation_create(recipient_email,'employer_employee','employer',e,null,e,now()+interval '7 days','qa-employee-directory');inv:=result->>'invitationId';
 if result->>'status'<>'pending' then raise exception 'Initial state wrong';end if;checks:=checks+1;
 result:=security.user_invitation_create(recipient_email,'employer_employee','employer',e,null,e,now()+interval '7 days','qa-employee-directory');
 if result->>'created'<>'false' or result->>'invitationId'<>inv then raise exception 'Duplicate invitation';end if;checks:=checks+1;
 begin perform security.user_invitation_accept(inv);raise exception 'Wrong recipient accepted';exception when others then if sqlerrm='Wrong recipient accepted' then raise;end if;end;checks:=checks+1;
 perform set_config('request.jwt.claim.sub',recipient_auth::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',recipient_auth,'email',recipient_email,'role','authenticated')::text,true);
 begin perform security.employee_workspace();raise exception 'Pending employee accessed workspace';exception when insufficient_privilege then null;end;checks:=checks+1;
 update public.wf_user_invitations set expires_at=now()-interval '1 minute' where invitation_id=inv;
 begin perform public.user_invitation_accept(inv);raise exception 'Expired invitation accepted';exception when others then if sqlerrm='Expired invitation accepted' then raise;end if;end;checks:=checks+1;
 update public.wf_user_invitations set expires_at=now()+interval '7 days',status='revoked' where invitation_id=inv;
 begin perform public.user_invitation_accept(inv);raise exception 'Revoked invitation accepted';exception when others then if sqlerrm='Revoked invitation accepted' then raise;end if;end;checks:=checks+1;
 update public.wf_user_invitations set status='pending' where invitation_id=inv;
 result:=public.user_invitation_accept(inv);
 if result->>'redirectTo'<>'/employee' then raise exception 'Employee routed to operations';end if;checks:=checks+1;
 if not security.employee_member(e) or security.employee_member(other_e) then raise exception 'Employee tenant boundary failed';end if;checks:=checks+1;
 result:=public.user_invitation_accept(inv);
 if result->>'idempotent'<>'true' then raise exception 'Acceptance replay not idempotent';end if;checks:=checks+1;
 if exists(select 1 from public.contractor_team_members where user_id=recipient_user and contractor_id=e) then raise exception 'Legacy team grant created';end if;checks:=checks+1;
 if security.member_of_employer(e) or security.has_employer_role(e,array['employer_owner','employer_admin','recruiter','hiring_manager','employer_read_only']) then raise exception 'Employee has operational role';end if;checks:=checks+1;
 if security.can_manage_employer_learning_content(e) then raise exception 'Employee can author training';end if;checks:=checks+1;
 if security.user_invitation_actor_can_manage('employer_admin','employer',e,null,e) or security.user_invitation_actor_can_manage('employer_employee','employer',e,null,e) then raise exception 'Employee can invite';end if;checks:=checks+1;
 begin perform security.employer_connections(e);raise exception 'Employee accessed operational directory';exception when insufficient_privilege then null;end;checks:=checks+1;
 execute 'set local role authenticated';
 result:=public.employee_workspace();
 execute 'set local role postgres';
 checks:=checks+1;
 if jsonb_array_length(result->'employers')<>1 or result->'employers'->0->>'id'<>e then raise exception 'Employee workspace leaked tenant';end if;checks:=checks+1;
 update public.app_role_memberships set status='cancelled' where auth_user_id=recipient_auth and role='employer_employee';
 begin perform security.employee_workspace();raise exception 'Revoked employee accessed';exception when insufficient_privilege then null;end;checks:=checks+1;
 update public.app_role_memberships set status='active' where auth_user_id=recipient_auth and role='employer_employee';
 update public.users set status='disabled' where user_id=recipient_user;
 begin perform security.employee_workspace();raise exception 'Disabled employee accessed';exception when insufficient_privilege then null;end;checks:=checks+1;
 update public.users set status='active' where user_id=recipient_user;
 if not exists(select 1 from public.platform_audit_events where entity_id=inv and action='USER_INVITATION_ACCEPTED') then raise exception 'Acceptance audit missing';end if;checks:=checks+1;
 perform set_config('request.jwt.claim.sub',owner_auth::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_auth,'role','authenticated')::text,true);
 result:=security.employer_connections(e);
 if not exists(select 1 from jsonb_array_elements(result->'people') p where p->>'userId'=recipient_user and p->>'role'='employer_employee') then raise exception 'Accepted employee absent from canvas data';end if;checks:=checks+1;
 begin perform security.employer_connections(other_e);raise exception 'Cross employer directory allowed';exception when insufficient_privilege then null;end;checks:=checks+1;
 if has_function_privilege('anon','public.employee_workspace()','execute') or has_function_privilege('authenticated','security.user_invitation_accept_before_employees(text)','execute') then raise exception 'Private facade/helper grants wrong';end if;checks:=checks+1;
 -- Institution admin options and accepted Students are available only in staff scope.
 select m.auth_user_id,m.scope_id into recipient_auth,institution from public.app_role_memberships m join public.users u on u.auth_user_id=m.auth_user_id where m.status='active' and u.status='active' and m.role in ('institution_super_admin','institution_admin') and m.scope_type='institution' limit 1;
 if recipient_auth is null then raise exception 'Institution admin fixture unavailable';end if;
 perform set_config('request.jwt.claim.sub',recipient_auth::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',recipient_auth,'role','authenticated')::text,true);
 result:=public.directory_invitation_options(institution);
 if not exists(select 1 from jsonb_array_elements(result->'roles') r where r->>'value'='student') or not exists(select 1 from jsonb_array_elements(result->'roles') r where r->>'value'='instructor') then raise exception 'Institution invitation options missing';end if;checks:=checks+1;
 if not exists(select 1 from jsonb_array_elements(public.institution_connections()->'people') p where p->>'role'='student' and p->>'institutionId'=institution) then raise exception 'Institution Students absent from directory';end if;checks:=checks+1;
 if exists(select 1 from jsonb_array_elements(result->'scopes') sc where sc->>'institutionId'<>institution) then raise exception 'Invitation scope leaked institution';end if;checks:=checks+1;
 -- Student peers must not appear in the institution read model.
 select p.student_id,p.school_id,u.auth_user_id into student_id,institution,recipient_auth from public.wf_student_profiles p join public.users u using(user_id) where lower(u.status)='active' and u.auth_user_id is not null and exists(select 1 from public.app_role_memberships m where m.auth_user_id=u.auth_user_id and m.role='student' and m.status='active') and not exists(select 1 from public.app_role_memberships m where m.auth_user_id=u.auth_user_id and m.role<>'student' and m.role<>'employer_employee' and m.status='active') limit 1;
 if student_id is null then raise exception 'Student-only fixture unavailable';end if;
 perform set_config('request.jwt.claim.sub',recipient_auth::text,true);perform set_config('request.jwt.claims',jsonb_build_object('sub',recipient_auth,'role','authenticated')::text,true);
 if exists(select 1 from jsonb_array_elements(security.institution_connections()->'people') p where p->>'role'='student') then raise exception 'Student peer privacy breached';end if;checks:=checks+1;
 if jsonb_array_length(security.directory_invitation_options(institution)->'roles')<>0 then raise exception 'Student has directory invitation options';end if;checks:=checks+1;
 perform set_config('qa.directory_employee_checks',checks::text,true);
end $$;
select jsonb_build_object('result','PASS','assertions',current_setting('qa.directory_employee_checks')::integer) directory_employee_verification;
