-- Run inside BEGIN with the new migration, then ROLLBACK. Never leave fixture awards/programs.
do $$
declare s text; u text; second text; admin uuid; student_auth uuid; employer_auth uuid; employer text; pid uuid; aid uuid; checkin uuid; rid uuid; sub uuid; summary jsonb; n integer; skill public.wf_student_skills%rowtype; verifier text; assignment public.wf_micro_cert_assignments%rowtype; completion text;
begin
 select p.student_id,p.user_id,usr.auth_user_id into s,u,student_auth from public.wf_student_profiles p join public.users usr on usr.user_id=p.user_id where usr.status='active' and exists(select 1 from public.app_role_memberships m where m.auth_user_id=usr.auth_user_id and m.role='student' and m.status='active') limit 1;
 select user_id into second from public.users where status='active' and user_id<>u limit 1;
 select usr.auth_user_id into admin from public.users usr join public.app_role_memberships m on m.auth_user_id=usr.auth_user_id where usr.status='active' and m.status='active' and m.scope_type='platform' and m.role in ('super_admin','admin','platform_admin') limit 1;
 if s is null or admin is null or second is null then raise exception 'Required staging fixtures unavailable'; end if;
 perform security.pro_award(s,'verified_skill','qa-1', '2026-10-05T17:00:00Z');
 perform security.pro_award(s,'verified_skill','qa-1', '2026-10-05T17:00:00Z');
 perform security.pro_award(s,'verified_skill','qa-2', '2026-10-05T17:00:00Z');
 perform security.pro_award(s,'verified_skill','qa-3', '2026-10-06T17:00:00Z');
 select sum(points) into n from public.wf_pro_ledger where student_id=s and source_key like 'qa-%';
 if n<>150 then raise exception 'Skill weekly event cap / duplicate failure: %',n; end if;
 perform security.pro_award(s,'training','qa-course-1', '2026-10-05T17:00:00Z');
 select points into n from public.wf_pro_ledger where student_id=s and source_key='qa-course-1';
 if n<>0 then raise exception 'Category daily cap failure'; end if;
 perform security.pro_award(s,'training','qa-course-2', '2026-10-06T17:00:00Z');
 perform security.pro_award(s,'training','qa-course-3', '2026-10-07T17:00:00Z');
 select sum(points) into n from public.wf_pro_ledger where student_id=s and rule_code='training';
 if n<>50 then raise exception 'Training repeat cap failure'; end if;
 perform security.pro_award(s,'check_in','qa-disabled', '2026-10-07T17:00:00Z');
 if exists(select 1 from public.wf_pro_ledger where source_key='qa-disabled') then raise exception 'Disabled source awarded'; end if;
 perform security.pro_reverse(s,'verified_skill','qa-1','QA invalidation');
 perform security.pro_reverse(s,'verified_skill','qa-1','QA repeated invalidation');
 select sum(points) into n from public.wf_pro_ledger where student_id=s and source_key='qa-1';
 if n<>0 then raise exception 'Idempotent reversal failure'; end if;
 perform security.pro_award(s,'training','qa-next-season', '2027-01-05T17:00:00Z');
 select season into strict summary from (select to_jsonb(season) season from public.wf_pro_ledger where source_key='qa-next-season') x;
 if summary<>to_jsonb('2027-01-01'::date) then raise exception 'Season boundary failure'; end if;
 -- Active Student can read self, but cannot author or spoof a source award.
 perform set_config('request.jwt.claims',jsonb_build_object('sub',student_auth,'role','authenticated')::text,true);
 perform set_config('request.jwt.claim.sub',student_auth::text,true);
 if security.pro_owner_access('platform','txkpro') then raise exception 'Student gained platform authority'; end if;
 begin perform security.pro_action(jsonb_build_object('op','create_program','ownerType','platform','ownerId','txkpro'));raise exception 'Student authoring allowed'; exception when insufficient_privilege then null;end;
 summary:=security.pro_workspace();
 if summary->'summary'->'progress' is null then raise exception 'Self progress missing'; end if;
 -- Platform admin program creation, privacy-safe workspace, no answer key disclosure.
 perform set_config('request.jwt.claims',jsonb_build_object('sub',admin,'role','authenticated')::text,true);
 perform set_config('request.jwt.claim.sub',admin::text,true);
 pid:=(security.pro_action(jsonb_build_object('op','create_program','ownerType','platform','ownerId','txkpro','name','QA '||gen_random_uuid(),'template','competition','startsAt',now()-interval '1 day','endsAt',now()+interval '7 days','terms','QA terms'))->>'id')::uuid;
 aid:=(security.pro_action(jsonb_build_object('op','create_activity','programId',pid,'title','QA trivia','kind','trivia','audience','student','instructions','Question?','points',5,'repeat','daily','dailyCap',10,'weeklyCap',50,'weekdays',jsonb_build_array(1,2,3,4,5,6,7),'options',jsonb_build_array('A','B'),'answerIndex',0))->>'id')::uuid;
 checkin:=(security.pro_action(jsonb_build_object('op','create_activity','programId',pid,'title','QA daily check-in','kind','check_in','audience','student','instructions','Provide evidence','points',5,'repeat','daily','dailyCap',10,'weeklyCap',50,'weekdays',jsonb_build_array(1,2,3,4,5,6,7)))->>'id')::uuid;
 perform security.pro_action(jsonb_build_object('op','set_status','programId',pid,'status','active'));
 perform security.pro_action(jsonb_build_object('op','invite','programId',pid,'email',(select email from public.users where user_id=u),'kind','student'));
 begin perform security.pro_action(jsonb_build_object('op','create_activity','programId',pid));raise exception 'Activated rules mutated';exception when others then if sqlerrm='Activated rules mutated' then raise;end if;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',student_auth,'role','authenticated')::text,true);
 perform set_config('request.jwt.claim.sub',student_auth::text,true);
 begin perform security.pro_action(jsonb_build_object('op','submit','programId',pid,'activityId',aid,'answer',0));raise exception 'Pending participant submitted';exception when insufficient_privilege then null;end;
 perform security.pro_action(jsonb_build_object('op','accept','programId',pid,'termsVersion',1));
 sub:=(security.pro_action(jsonb_build_object('op','submit','programId',pid,'activityId',aid,'answer',0))->>'id')::uuid;
 perform security.pro_action(jsonb_build_object('op','submit','programId',pid,'activityId',aid,'answer',0));
 select count(*) into n from public.wf_incentive_score_ledger where submission_id=sub;
 if n<>1 then raise exception 'Duplicate private award';end if;
 if security.pro_workspace()::text like '%answerIndex%' or security.pro_workspace()::text like '%answer_index%' then raise exception 'Answer key leak';end if;
 select id into rid from public.wf_incentive_participants where program_id=pid and user_id=u;
 select sum(points) into n from public.wf_incentive_score_ledger where participant_id=rid;
 if n<>5 then raise exception 'Private trivia award failure';end if;
 if exists(select 1 from public.wf_pro_ledger where source_key=sub::text) then raise exception 'Private activity contaminated global score';end if;
 sub:=(security.pro_action(jsonb_build_object('op','submit','programId',pid,'activityId',checkin,'evidence','QA completed'))->>'id')::uuid;
 begin perform security.pro_program_report(pid);raise exception 'Participant report allowed';exception when insufficient_privilege then null;end;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',admin,'role','authenticated')::text,true);
 perform set_config('request.jwt.claim.sub',admin::text,true);
 insert into public.wf_pro_activity_days(student_id,family,day,source_key) select s,'check_in',(now() at time zone 'America/Chicago')::date-v,'qa' from generate_series(1,2) v;
 perform security.pro_action(jsonb_build_object('op','approve','programId',pid,'submissionId',sub,'reason','QA source verified'));
 if not exists(select 1 from public.wf_pro_system_badges where student_id=s and family='check_in' and tier=3 and status='earned') then raise exception 'Check-in badge missing';end if;
 perform security.pro_action(jsonb_build_object('op','reverse','programId',pid,'submissionId',sub,'reason','QA source invalidated'));
 select sum(points) into n from public.wf_incentive_score_ledger where submission_id=sub;
 if n<>0 or not exists(select 1 from public.wf_pro_system_badges where student_id=s and family='check_in' and tier=3 and status='revoked') then raise exception 'Evidence reversal/badge revocation failure';end if;
 perform security.pro_program_report(pid);
 if not exists(select 1 from public.wf_incentive_audit where program_id=pid and event='PROGRAM_REPORT_EXPORTED') then raise exception 'Report audit missing';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',student_auth,'role','authenticated')::text,true);
 perform set_config('request.jwt.claim.sub',student_auth::text,true);
 select m.auth_user_id,m.scope_id into employer_auth,employer from public.app_role_memberships m join public.users usr on usr.auth_user_id=m.auth_user_id join public.contractors c on c.contractor_id=m.scope_id where usr.status='active' and m.status='active' and m.role in ('employer_owner','employer_admin') and m.scope_type='employer' and c.account_status='active' and c.approval_status='approved' and not exists(select 1 from public.app_role_memberships platform where platform.auth_user_id=m.auth_user_id and platform.status='active' and platform.scope_type='platform') limit 1;
 if employer_auth is null then raise exception 'Employer fixture unavailable';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',employer_auth,'role','authenticated')::text,true);
 perform set_config('request.jwt.claim.sub',employer_auth::text,true);
 if not security.pro_owner_access('employer',employer) or security.pro_owner_access('employer','unrelated-employer-qa') or security.pro_owner_access('platform','txkpro') then raise exception 'Employer role and scope boundary failure';end if;
 begin perform security.pro_action(jsonb_build_object('op','set_status','programId',pid,'status','ended'));raise exception 'Cross-owner program mutation allowed';exception when insufficient_privilege then null;end;
 if exists(select 1 from jsonb_array_elements(security.pro_workspace()->'programs') x where x->>'id'=pid::text) then raise exception 'Cross-owner program disclosed';end if;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',student_auth,'role','authenticated')::text,true);
 perform set_config('request.jwt.claim.sub',student_auth::text,true);
 -- No direct access to ledgers/answer keys, no raw-award API, no anonymous workspace.
 if has_table_privilege('authenticated','public.wf_incentive_activities','select') or has_table_privilege('authenticated','public.wf_pro_ledger','insert') then raise exception 'Direct table access';end if;
 if has_function_privilege('authenticated','security.pro_award(text,text,text,timestamp with time zone,text)','execute') or has_function_privilege('anon','public.pro_workspace()','execute') or has_function_privilege('authenticated','public.pro_public(text)','execute') then raise exception 'Unchecked helper exposed';end if;
 -- A three-day visit earns an enduring System badge, not points.
 insert into public.wf_pro_activity_days(student_id,family,day,source_key) select s,'visit',(now() at time zone 'America/Chicago')::date-v,'qa' from generate_series(1,2) v;
 perform security.pro_visit();perform security.pro_visit();
 if not exists(select 1 from public.wf_pro_system_badges where student_id=s and family='visit' and tier=3) then raise exception 'Visit tier missing';end if;
 if (security.pro_streak(s,'visit')->>'current')::integer<>3 then raise exception 'Visit dedup/streak failure';end if;
 -- Actual canonical source transitions, rather than only exercising the internal calculator.
 select ss.* into skill from public.wf_student_skills ss join public.wf_student_profiles student on student.student_id=ss.student_id where exists(select 1 from public.users reviewer join public.app_role_memberships m on m.auth_user_id=reviewer.auth_user_id where reviewer.status='active' and m.status='active' and m.role='instructor' and security.institution_scope_matches(student.school_id,m.scope_type,m.scope_id,student.cohort_id)) limit 1;
 if skill.id is null then raise exception 'Canonical skill fixture unavailable';end if;
 update public.wf_student_skills set verified_at=verified_at where id=skill.id;
 if exists(select 1 from public.wf_pro_ledger where source_ref=skill.student_skill_id) then raise exception 'Historical cosmetic skill backfilled';end if;
 select reviewer.user_id into verifier from public.users reviewer join public.app_role_memberships m on m.auth_user_id=reviewer.auth_user_id join public.wf_student_profiles student on student.student_id=skill.student_id where reviewer.status='active' and m.status='active' and m.role='instructor' and security.institution_scope_matches(student.school_id,m.scope_type,m.scope_id,student.cohort_id) limit 1;
 update public.wf_student_skills set status='ready_for_review',provenance='self_attested',verified_by_user_id=null,verified_at=null,revoked_at=null where id=skill.id;
 update public.wf_student_skills set status='verified',provenance='institution_verified',verified_by_user_id=verifier,verified_at=now() where id=skill.id;
 update public.wf_student_skills set verified_at=verified_at where id=skill.id;
 select count(*) into n from public.wf_pro_ledger where source_ref=skill.student_skill_id and entry_type='award';
 if n<>1 then raise exception 'Canonical skill trigger/dedup failure';end if;
 update public.wf_student_skills set status='revoked',revoked_at=now() where id=skill.id;
 select sum(points) into n from public.wf_pro_ledger where student_id=skill.student_id and rule_code='verified_skill' and source_key=skill.skill_id;
 if n<>0 then raise exception 'Canonical skill invalidation failure';end if;
 select a.* into assignment from public.wf_micro_cert_assignments a join public.wf_employer_micro_cert_versions v on v.micro_cert_version_id=a.micro_cert_version_id join public.wf_employer_micro_certs c on c.micro_cert_id=a.micro_cert_id where c.active and a.status<>'cancelled' limit 1;
 if assignment.id is null then raise exception 'Canonical training fixture unavailable';end if;
 -- No staging course is live yet. Promote only this rollback fixture to test future source transitions.
 update public.wf_employer_micro_cert_versions set status='live',published_at=now() where micro_cert_version_id=assignment.micro_cert_version_id;
 completion:='QA-'||gen_random_uuid()::text;
 insert into public.wf_micro_cert_completions(completion_id,assignment_id,attempt_number,outcome,score,evidence,completed_at) values(completion,assignment.assignment_id,(select coalesce(max(attempt_number),0)+1 from public.wf_micro_cert_completions where assignment_id=assignment.assignment_id),'passed',100,'{}',now());
 if not exists(select 1 from public.wf_pro_ledger where student_id=assignment.student_id and rule_code='training' and source_ref=completion) then raise exception 'Canonical training trigger failure';end if;
 update public.wf_micro_cert_assignments set status='cancelled' where id=assignment.id;
 if not exists(select 1 from public.wf_pro_ledger where student_id=assignment.student_id and rule_code='training' and source_key=assignment.micro_cert_id and entry_type='reversal') then raise exception 'Canonical assignment reversal failure';end if;
 if security.pro_public('/students/nonexistent-qa-profile') is not null then raise exception 'Public profile gate bypass';end if;
 if exists(select 1 from public.wf_incentive_pool_ledger) then raise exception 'Funding unexpectedly activated';end if;
end $$;
select jsonb_build_object('result','PASS','checks',jsonb_build_array('source_dedup','skill_event_cap','category_daily_cap','training_event_cap','disabled_sources','idempotent_reversal','season_boundary','student_authoring_denied','self_summary','terms_freeze','pending_submit_denied','acceptance','trivia_award','answer_key_private','private_global_separation','table_privileges','helper_privileges','visit_dedup','visit_tier','funding_disabled','checkin_review','private_score_reversal','checkin_badge_revocation','report_scope','report_audit','public_profile_gate','employer_role_scope','cross_owner_mutation','cross_owner_read','no_historical_backfill','skill_source_transition','skill_source_invalidation','training_source_transition','assignment_source_invalidation')) verification;
